from enum import IntEnum


# class ParameterCategory:

class MeteorologicalCategory(IntEnum):
    TEMPERATURE = 0
    MOISTURE = 1
    MOMENTUM = 2
    MASS = 3
    SHORT_WAVE_RADIATION = 4
    LONG_WAVE_RADIATION = 5
    CLOUD = 6
    THERMODYNAMIC_STABILITY_INDICES = 7
    KINEMATIC_STABILITY_INDICES = 8
    TEMPERATURE_PROBABILITY = 9
    MOISTURE_PROBABILITY = 10
    MOMENTUM_PROBABILITY = 11
    MASS_PROBABILITY = 12
    AEROSOLS = 13
    TRACE_GASES = 14
    RADAR = 15
    FORECAST_RADAR = 16
    ELECTRODYNAMICS = 17
    NUCLEAR_RADIATION = 18
    PHYSICAL_ATMOSPHERE = 19
    ATMOSPHERE_CHEMISTRY = 20
    THERMODYNAMIC_PROPERTIES = 21,
    DROUGHT_INDICES = 22
    CCITT_IA5 = 190
    MISCELLANEOUS = 191
    COVARIANCE = 192
    LOCAL_USE = 193
    MISSING = 255


class ParameterCategory:
    _category: IntEnum
    _category_value: int


class HydrologicalCategories(IntEnum):
    HYDROLOGY_BASIC = 0
    HYDROLOGY_PROCESSES = 1
    HYDROLOGY_MODEL_PARAMETERS = 2
    VOLCANIC_ACTIVITY = 3
    SURFACE_AND_SUBSURFACE_WATER = 4
    MULTICATEGORY_HYDROLOGY = 255


class LandSurfaceCategories(IntEnum):
    VEGETATION_BURNING = 0
    STRATA_PARAMETERS = 1
    LAND_INFO = 2
    ICE_RELEASE_AT_A_RELATED_LOCATION = 3
    COASTAL_ROCK_SPATIAL_MOMENTS = 4
