from model.grib2.parameter import Parameter, Unit

meteorological_thermodynamic_stability = {
    0: Parameter(id=0, name='Parcel Lifted Index (to 500 hPa)', unit=Unit.KELVIN, abbrev='PLI'),
    1: Parameter(id=1, name='Best Lifted Index (to 500 hPa)', unit=Unit.KELVIN, abbrev='BLI'),
    2: Parameter(id=2, name='K Index', unit=Unit.KELVIN, abbrev='KX'),
    3: Parameter(id=3, name='KO Index', unit=Unit.KELVIN, abbrev='KOX'),
    4: Parameter(id=4, name='Total Totals Index', unit=Unit.KELVIN, abbrev='TOTALX'),
    5: Parameter(id=5, name='Sweat Index', unit=Unit.NUMERIC, abbrev='SX'),
    6: Parameter(id=6, name='Convective Available Potential Energy', unit=Unit.JULES_PER_KG, abbrev='CAPE'),
    7: Parameter(id=7, name='Convective Inhibition', unit=Unit.JULES_PER_KG, abbrev='CIN'),
    8: Parameter(id=8, name='Storm Relative Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED, abbrev='HLCY'),
    9: Parameter(id=9, name='Energy Helicity Index', unit=Unit.NUMERIC, abbrev='EHLX'),
    10: Parameter(id=10, name='Surface Lifted Index', unit=Unit.KELVIN, abbrev='LFT X'),
    11: Parameter(id=11, name='Best (4 layer) Lifted Index', unit=Unit.KELVIN, abbrev='4LFTX'),
    12: Parameter(id=12, name='Richardson Number', unit=Unit.NUMERIC, abbrev='RI'),
    13: Parameter(id=13, name='Showalter Index', unit=Unit.KELVIN, abbrev='SHWINX'),
    15: Parameter(id=15, name='Updraft Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED, abbrev='UPHL'),
    16: Parameter(id=16, name='Bulk Richardson Number', unit=Unit.NUMERIC, abbrev='BLKRN'),
    17: Parameter(id=17, name='Gradient Richardson Number', unit=Unit.NUMERIC, abbrev='GRDRN'),
    18: Parameter(id=18, name='Flux Richardson Number', unit=Unit.NUMERIC, abbrev='FLXRN'),
    19: Parameter(id=19, name='Convective Available Potential Energy Shear', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED,
                  abbrev='CONAPES'),
    20: Parameter(id=20, name='Thunderstorm intensity index', abbrev='TIIDEX'),
    192: Parameter(id=192, name='Surface Lifted Index', unit=Unit.KELVIN, abbrev='LFT X'),
    193: Parameter(id=193, name='Best (4 layer) Lifted Index', unit=Unit.KELVIN, abbrev='4LFTX'),
    194: Parameter(id=194, name='Richardson Number', unit=Unit.NUMERIC, abbrev='RI'),
    195: Parameter(id=195, name='Convective Weather Detection Index', abbrev='CWDI'),
    196: Parameter(id=196, name='Ultra Violet Index', unit=Unit.WATTS_PER_METER_SQUARED, abbrev='UVI'),
    197: Parameter(id=197, name='Updraft Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED, abbrev='UPHL'),
    198: Parameter(id=198, name='Leaf Area Index', unit=Unit.NUMERIC, abbrev='LAI'),
    199: Parameter(id=199, name='Hourly Maximum of Updraft Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED,
                   abbrev='MXUPHL'),
    200: Parameter(id=200, name='Hourly Minimum of Updraft Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED,
                   abbrev='MNUPHL'),
    201: Parameter(id=201, name='Bourgoiun Negative Energy Layer (surface to freezing level)', unit=Unit.JULES_PER_KG,
                   abbrev='BNEGELAY'),
    202: Parameter(id=202, name='Bourgoiun Positive Energy Layer (2k ft AGL to 400 hPa)', unit=Unit.JULES_PER_KG,
                   abbrev='BPOSELAY'),
    203: Parameter(id=203, name='Downdraft CAPE', unit=Unit.JULES_PER_KG, abbrev='DCAPE'),
    204: Parameter(id=204, name='Effective Storm Relative Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED,
                   abbrev='EFHL'),
    205: Parameter(id=205, name='Enhanced Stretching Potential', unit=Unit.NUMERIC, abbrev='ESP'),
    206: Parameter(id=206, name='Critical Angle', unit=Unit.DEGREE, abbrev='CANGLE'),
    207: Parameter(id=207, name='Effective Surface Helicity', unit=Unit.SQUARE_METERS_PER_SECOND_SQUARED,
                   abbrev='E3KH'),
    208: Parameter(id=208, name='Significant Tornado Parameter with CIN-Effective Layer', unit=Unit.NUMERIC,
                   abbrev='STPC'),
    209: Parameter(id=209, name='Significant Hail Parameter', unit=Unit.NUMERIC, abbrev='SIGH'),
    210: Parameter(id=210, name='Supercell Composite Parameter-Effective Layer', unit=Unit.NUMERIC, abbrev='SCCP'),
    211: Parameter(id=211, name='Significant Tornado parameter-Fixed Layer', unit=Unit.NUMERIC, abbrev='SIGT'),
    212: Parameter(id=212, name='Mixed Layer (100 mb) Virtual LFC', unit=Unit.NUMERIC, abbrev='MLFC'),
    255: Parameter(id=255, name="Missing")
}
